// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQkrNi9IS2JejhephuvQOpR2Oz7ChSKHI',
    appId: '1:895275598043:android:7043f9476688300daaccfe',
    messagingSenderId: '895275598043',
    projectId: 'your-basket-515fc',
    storageBucket: 'your-basket-515fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-MC9TwBVi4EgfjCD4sRS3bfUh6P5SdwU',
    appId: '1:895275598043:ios:06654d55840ce54caaccfe',
    messagingSenderId: '895275598043',
    projectId: 'your-basket-515fc',
    storageBucket: 'your-basket-515fc.appspot.com',
    androidClientId: '895275598043-1ntt2ebus84nu01gt0l9tgcqqjsfmpi4.apps.googleusercontent.com',
    iosClientId: '895275598043-hkbi4oklc1kho87midae5j7c1ho25oq2.apps.googleusercontent.com',
    iosBundleId: 'com.buztron.basko',
  );
}
