// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9Tlp_LbsonD_liNj6c_q8eydE9-BTDDs',
    appId: '1:895275598043:web:9daa8fc624edf171aaccfe',
    messagingSenderId: '895275598043',
    projectId: 'your-basket-515fc',
    authDomain: 'your-basket-515fc.firebaseapp.com',
    storageBucket: 'your-basket-515fc.appspot.com',
    measurementId: 'G-G1K14Q6WQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQkrNi9IS2JejhephuvQOpR2Oz7ChSKHI',
    appId: '1:895275598043:android:269761cb3962e28caaccfe',
    messagingSenderId: '895275598043',
    projectId: 'your-basket-515fc',
    storageBucket: 'your-basket-515fc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-MC9TwBVi4EgfjCD4sRS3bfUh6P5SdwU',
    appId: '1:895275598043:ios:f19930a7c2f93e7daaccfe',
    messagingSenderId: '895275598043',
    projectId: 'your-basket-515fc',
    storageBucket: 'your-basket-515fc.appspot.com',
    androidClientId: '895275598043-7cn6lcnsp47tl32n1hp40hpqhpvqbcse.apps.googleusercontent.com',
    iosClientId: '895275598043-2a7n1vtl7nvveuq9iti74lf1girusb7j.apps.googleusercontent.com',
    iosBundleId: 'com.example.yourBasket',
  );
}
